// =============================================================================
//  environment/Turbulence.hpp
//
//  Continuous atmospheric turbulence as a Dryden-form gust model. Each axis is
//  generated by passing white noise through a shaping filter whose stationary
//  variance equals the turbulence intensity sigma^2 and whose correlation
//  length is the Dryden scale length L. Implemented as a first-order
//  Gauss-Markov (exponentially-correlated) process -- the discrete form of the
//  Dryden longitudinal filter -- which preserves the variance exactly and gives
//  realistic, frame-rate-independent gusts:
//
//        beta = V / L
//        phi  = exp(-beta * dt)
//        g[k+1] = phi * g[k] + sigma * sqrt(1 - phi^2) * w,   w ~ N(0,1)
//
//  Gusts are produced as NED velocity perturbations (horizontal sigma for N/E,
//  a smaller vertical sigma for D) and added to the steady wind. Because the
//  aerodynamics work from the air-relative velocity, a vertical gust changes the
//  angle of attack and a horizontal gust changes airspeed/sideslip naturally.
//
//  The RNG is seeded for reproducibility (tests, replays).
// =============================================================================
#pragma once

#include "core/Math.hpp"

#include <cmath>
#include <random>

namespace fsim {

class DrydenTurbulence {
public:
    struct Params {
        double sigmaHorizontal{0.0}; // m/s RMS for N/E gusts (0 = calm)
        double sigmaVertical{0.0};   // m/s RMS for vertical gusts
        double scaleHorizontal{533.0}; // L_u/L_v, m (~1750 ft, MIL-F-8785C high alt)
        double scaleVertical{533.0};   // L_w, m
    };

    // Intensity presets (RMS values per common turbulence categories).
    static Params light()    { return {1.5, 0.9, 533.0, 533.0}; }
    static Params moderate() { return {3.5, 2.1, 533.0, 533.0}; }
    static Params severe()   { return {6.5, 3.9, 533.0, 533.0}; }

    DrydenTurbulence() = default;
    explicit DrydenTurbulence(const Params& p, unsigned seed = 1u)
        : p_(p), rng_(seed) {}

    void setParams(const Params& p) { p_ = p; }
    void reset() { gust_ = Vec3{0, 0, 0}; }

    // Advance one step and return the current NED gust velocity (m/s).
    Vec3 update(double dt, double airspeed) {
        const double V = std::max(airspeed, 1.0);
        gust_.x = step(gust_.x, V, p_.scaleHorizontal, p_.sigmaHorizontal, dt);
        gust_.y = step(gust_.y, V, p_.scaleHorizontal, p_.sigmaHorizontal, dt);
        gust_.z = step(gust_.z, V, p_.scaleVertical,   p_.sigmaVertical,   dt);
        return gust_;
    }

    const Vec3& gust() const { return gust_; }

private:
    Params p_;
    Vec3   gust_{};
    std::mt19937 rng_;
    std::normal_distribution<double> normal_{0.0, 1.0};

    double step(double current, double V, double L, double sigma, double dt) {
        if (sigma <= 0.0 || L <= 0.0) return 0.0;
        const double beta = V / L;
        const double phi  = std::exp(-beta * dt);
        const double drive = sigma * std::sqrt(std::max(0.0, 1.0 - phi * phi));
        return phi * current + drive * normal_(rng_);
    }
};

} // namespace fsim
